services:

    cells:
        image: pydio/cells:latest
        hostname: pydio-cells
        container_name: pydio-cells
        restart: unless-stopped
        healthcheck:
            test: ["CMD-SHELL", "wget -nv -t1 --spider http://pydio-cells:8080 || exit 1"]
            interval: 1m
            timeout: 10s
            retries: 3
        networks:
            pydio:
                ipv4_address: ${IPv4}
            pydio-internal:
        ports:
            - "${HOST_PORT}:8080"
        volumes:
            - cells:/var/cells
            - data:/var/cells/data

    mysql:
        image: mysql:8.0
        hostname: pydio-mysql
        container_name: pydio-mysql
        restart: unless-stopped
        command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci]
        healthcheck:
            test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -p${MYSQL_ROOT_PASSWORD} || exit 1"]
            interval: 1m
            timeout: 10s
            retries: 3
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: pydio
            MYSQL_USER: pydio
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        networks:
            - pydio-internal
        volumes:
            - mysql:/var/lib/mysql

volumes:
    cells:
        name: pydio-cells
        driver: local
    data:
        name: pydio-data
        driver: local
    mysql:
        name: pydio-mysql
        driver: local

networks:
    pydio:
        name: pydio
        driver: bridge
        ipam:
            config:
                - subnet: ${SUBNET}
                  gateway: ${GATEWAY}
    pydio-internal:
        name: pydio-internal
        driver: bridge
        ipam:
            config:
                - subnet: ${SUBNET_INTERNAL}
                  gateway: ${GATEWAY_INTERNAL}
