services:

    dokku:
        image: dokku/dokku:0.35.20
        hostname: dokku
        container_name: dokku
        restart: unless-stopped
        healthcheck:
            test: ["CMD-SHELL", "touch /tmp/health.txt"]
            interval: 1m
            timeout: 10s
            retries: 3
            start_interval: 10s
            start_period: 1m
        environment:
            DOKKU_HOSTNAME: ${DOKKU_HOSTNAME}
            DOKKU_HOST_ROOT: /mnt/dokku/home/dokku
            DOKKU_LIB_HOST_ROOT: /mnt/dokku/var/lib/dokku
        # networks:
        #     dokku:
        #         ipv4_address: ${IPv4}
        network_mode: bridge
        ports:
            - "${HOST_PORT_SSH}:22"
            - "${HOST_PORT_WEB}:80"
            - "${HOST_PORT_SSL}:443"
        volumes:
            - dokku-data:/mnt/dokku
            - /var/run/docker.sock:/var/run/docker.sock

volumes:
    dokku-data:
        name: dokku-data
        driver: local

# networks:
#     dokku:
#         name: dokku
#         driver: bridge
#         ipam:
#             config:
#                 - subnet: ${SUBNET}
#                   gateway: ${GATEWAY}
