services:
  vertd:
    container_name: vertd
    image: ghcr.io/vert-sh/vertd:latest
    build: .
    environment:
      - WEBHOOK_URL=${WEBHOOK_URL}
      - WEBHOOK_PINGS=${WEBHOOK_PINGS}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - PUBLIC_URL=${PUBLIC_URL}
    ports:
      - "${PORT:-24153}:24153"
