services:
  concretecms:
    image: ghcr.io/concrete5-community/docker5:latest
    ports:
      - "8081:80"
    depends_on:
      - database
    environment:
      # These variables are used by the image's startup script to check the DB link
      DB_SERVER: database
      DB_USER: dbuser_cms
      DB_PASSWORD: MySecr3tPa55w0rd
      DB_NAME: mycmsdatabase
    volumes:
      # Use bind mounts for development to see real-time code changes
      # Replace /path/to/my/concretecms/ with the local path to your project files
      - ./application/files:/var/www/localhost/htdocs/application/files
      - ./application/config:/var/www/localhost/htdocs/application/config
      - ./packages:/var/www/localhost/htdocs/packages
      - ./application/blocks:/var/www/localhost/htdocs/application/blocks

  database:
    image: mariadb:latest
    environment:
      MYSQL_DATABASE: mycmsdatabase
      MYSQL_USER: dbuser_cms
      MYSQL_PASSWORD: MySecr3tPa55w0rd
      MYSQL_ROOT_PASSWORD: MyS3cr3tR00tPa55w0rd
    volumes:
      # Use a named volume for persistent database data
      - db_data:/var/lib/mysql

volumes:
  db_data:
