#!/usr/bin/env bash
####################################################################
# Author:       Ragdata
# Date:         16/02/2026
# License:      MIT License
# Copyright:    Copyright © 2026 Redeyed Technologies
####################################################################
# INSTALL DOCKER ROOTLESS
####################################################################
sudo loginctl enable-linger "$(whoami)"

sudo apt install -y dbus-user-session

systemctl --user start dbus

sudo apt install -y uidmap

sudo mkdir -p /etc/systemd/system/"$(whoami)"@.service.d

cat <<EOF | sudo tee /etc/systemd/system/"$(whoami)"@.service.d/delegate.conf
[Service]
Delegate=cpu cpuset io memory pids
EOF

sudo systemctl daemon-reload

cat <<EOT | sudo tee "/etc/apparmor.d/usr.local.bin.rootlesskit"
abi <abi/4.0>,
include <tunables/global>

/home/"$(whoami)"/bin/rootlesskit flags=(unconfined) {
  userns,

  # Site-specific additions and overrides. See local/README for details.
  include if exists <local/usr.local.bin.rootlesskit>
}
EOT

sudo systemctl restart apparmor.service

curl -fsSL https://get.docker.com | sh

dockerd-rootless-setuptool.sh install
