#!/usr/bin/env bash
####################################################################
# Author:       Ragdata
# Date:         03/06/2025
# License:      MIT License
# Copyright:    Copyright © 2025 Redeyed Technologies
####################################################################
# INSTALL DOCKER
####################################################################

# Check if the script is run as root
if [ "$(id -u)" -ne 0 ]; then
	echo "This script must be run as root. Use 'sudo' to run it."
	exit 1
fi

for pkg in docker.io docker-doc docker-compose docker-compose-v2 podman-docker containerd runc; do apt purge -y $pkg; done

apt update -y

apt install -y apt-transport-https ca-certificates curl software-properties-common

install -m 0755 -d /etc/apt/keyrings

curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc

chmod a+r /etc/apt/keyrings/docker.asc

if [[ ! -f /etc/apt/sources.list.d/docker.list ]]; then
	echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
  $(. /etc/os-release && echo "${UBUNTU_CODENAME:-$VERSION_CODENAME}") stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
fi

apt update -y

apt install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin docker-ce-rootless-extras

cp etc/docker/daemon.json /etc/docker/daemon.json

systemctl enable docker

systemctl restart docker

echo "Docker has been installed successfully."
