services:

    newt:
        image: fosrl/newt:latest
        hostname: newt
        container_name: newt
        environment:
            PANGOLIN_ENDPOINT: ${PANGOLIN_ENDPOINT}
            NEWT_ID: ${NEWT_ID}
            NEWT_SECRET: ${NEWT_SECRET}
            DOCKER_SOCKET: /var/run/docker.sock
        # networks:
        #     newt:
        #         ipv4_address: ${IPv4}
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - /etc/localtime:/etc/localtime:ro
            - /etc/timezone:/etc/timezone:ro

# networks:
#     newt:
#         name: newt
#         driver: bridge
#         driver_opts:
#             encrypted: "true"
#         ipam:
#             config:
#                 - subnet: ${SUBNET}
#                   gateway: ${GATEWAY}
