services:

    newt:
        image: fosrl/newt:latest
        hostname: newt
        environment:
            PANGOLIN_ENDPOINT: ${PANGOLIN_ENDPOINT}
            NEWT_ID: ${NEWT_ID}
            NEWT_SECRET: ${NEWT_SECRET}
            DOCKER_SOCKET: /var/run/docker.sock
        networks:
            newt:
                aliases:
                    - newt
                    - newt.local
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - /etc/localtime:/etc/localtime:ro
            - /etc/timezone:/etc/timezone:ro

networks:
    newt:
        driver: bridge
        driver_opts:
            encrypted: "true"
            attachable: "true"
        ipam:
            config:
                - subnet: ${SUBNET}
