services:

    vaultwarden:
        image: vaultwarden/server:latest
        hostname: vaultwarden
        container_name: vaultwarden
        restart: unless-stopped
        healthcheck:
            test: ["CMD-SHELL", "curl --fail http://vaultwarden:80 || exit 1"]
            interval: 1m
            timeout: 10s
            retries: 3
        environment:
            - ADMIN_TOKEN=${ADMIN_TOKEN}
            - SIGNUPS_ALLOWED=${SIGNUPS_ALLOWED}
            - WEBSOCKET_ENABLED=${WEBSOCKET_ENABLED}
            - SMTP_HOST=${SMTP_HOST}
            - SMTP_FROM=${SMTP_FROM}
            - SMTP_FROM_NAME=${SMTP_FROM_NAME}
            - SMTP_PORT=${SMTP_PORT}
            - SMTP_SECURITY=${SMTP_SECURITY}
            - SMTP_USERNAME=${SMTP_USERNAME}
            - SMTP_PASSWORD=${SMTP_PASSWORD}
            - SMTP_TIMEOUT=${SMTP_TIMEOUT}
            - DOMAIN=${DOMAIN}
        networks:
            vaultwarden:
                ipv4_address: ${IPv4}
        ports:
          - "${HOST_PORT}:80"
        volumes:
            - vaultwarden-data:/data

volumes:
    vaultwarden-data:
        name: vaultwarden-data
        driver: local

networks:
    vaultwarden:
        name: vaultwarden
        driver: bridge
        ipam:
            config:
                - subnet: ${SUBNET}
                  gateway: ${GATEWAY}
