services:

    minio:
        image: quay.io/minio/minio
        hostname: minio
        container_name: minio
        restart: unless-stopped
        command: server /data --console-address ":9001"
        healthcheck:
            test: ["CMD-SHELL", "touch /tmp/health.txt"]
            interval: 1m
            timeout: 10s
            retries: 3
            start_interval: 10s
            start_period: 1m
        environment:
            MINIO_ROOT_USER: ${MINIO_ROOT_USER}
            MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
        networks:
            minio:
                ipv4_address: ${IPv4}
        ports:
            - 9000:9000
            - 9001:9001
        volumes:
            - minio-data:/data
            - /etc/localtime:/etc/localtime:ro
            - /etc/timezone:/etc/timezone:ro

volumes:
    minio-data:
        name: minio-data
        driver: local

networks:
    minio:
        name: minio
        driver: bridge
        ipam:
            config:
                - subnet: ${SUBNET}
                  gateway: ${GATEWAY}
